### ISSUE TITLE
Le lien sur l'aide de l'extracteur ne fonctionne pas

### ISSUE THREAD

**Issue by mathieubecker** [isogeo/doc-homepage#3]
> Page d'accueil help.isogeo.com
> clic sur "Extracteur de données Isogeo" (http://help.isogeo.com/extractor/fr/index.html)
> reste sur la page d'accueil

**Comment by Guts** [comment]
Corrigé : l'aide de l'extracteur n'avait pas été poussée en PROD depuis l'été dernier.
